# Generated by Django 4.2.6 on 2023-10-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_type',
            field=models.CharField(default='Default Cover Type', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(default='N/A', max_length=13),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default='Unknown Publisher', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_age',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
