# Generated by Django 4.2.6 on 2023-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_author_product_cover_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recommended_age',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
