# Generated by Django 4.2.6 on 2023-10-20 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_recommended_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
