# Generated by Django 4.2.6 on 2023-10-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
