# Generated by Django 4.2.6 on 2023-10-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publication_date',
            new_name='publication_datee',
        ),
    ]
