# Generated by Django 4.2.6 on 2023-10-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_publication_datee_product_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publication_date',
        ),
    ]
