# Generated by Django 4.2.6 on 2023-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_publication_date_alter_product_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
    ]
