# Generated by Django 4.2.6 on 2023-11-09 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_alter_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentariu', models.TextField()),
                ('scor', models.IntegerField(default=0)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
